version: '3.4'

services:
  payments.web:
    image: ${DOCKER_REGISTRY-}paymentsweb
    container_name: payments_web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - payments.db

  payments.db:
    image: postgres:13.2
    container_name: payments_db
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
